name: Build and deploy
on:
  push:
    branches:
      - main
jobs:
  package:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install packages
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.3
          run_install: |
            - recursive: true
              args: [--frozen-lockfile]
      - name: Package scripts
        run: pnpm package
      - name: Branch and commit
        run: |
          git status
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git checkout -b package-scripts
          git add .
          git status
          git commit -a -m "Add changes"
