name: Build and deploy
on:
  push:
    branches:
      - main
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install packages
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.3
          run_install: |
            - recursive: true
              args: [--frozen-lockfile]
      - name: Package scripts
        run: pnpm package
